version: "3.5"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/aeryilma/data/wordpress/.
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aeryilma/data/mariadb/.

services:
  nginx:
    container_name: c_nginx
    build: ./requirements/nginx/.
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/wordpress
    env_file:
     - .env
    networks:
     - inception
    restart: always
    depends_on:
     - wordpress
  wordpress:
    container_name: c_wordpress
    build: ./requirements/wordpress/.
    expose:
     - "9000"
    volumes:
     - wordpress:/var/www/wordpress
    env_file:
     - .env
    networks:
     - inception
    restart: always
    depends_on:
     - mariadb
  mariadb:
    container_name: c_mariadb
    build: ./requirements/mariadb/.
    ports:
     - "3306:3306"
    volumes:
     - mariadb:/var/lib/mysql
    env_file:
     - .env
    networks:
     - inception
    restart: always
  portrainer:
    container_name: c_portrainer
    image: portainer/portainer-ce
    ports:
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/aeryilma/data/portrainer:/data
  adminer:
    container_name: c_adminer
    image: adminer
    ports:
     - "9001:8080"
    links:
     - wordpress
     - mariadb 
    restart: always
